<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>2Dark Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i)\b[\d.]+\b</string>
			<key>name</key>
			<string>constant.numeric.2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(LeftHandCategory|Exit|SetEventHearAttributes|Attribute|SetVisionDistance|SetVisionAperture|SetEarDistance|ReplaceAttribute|Attribute|AttributesContains|Wait_GotoFlag|Wait_GotoFlagPath|Wait_FollowPath|RightHandCategory|IsInHand|DiscoverItem|Type|SourceType|TriggerType)\b</string>
			<key>name</key>
			<string>invalid.deprecated.2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(Version)\b</string>
			<key>name</key>
			<string>support.function.2dark_script</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.2dark_script</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.2dark_script</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.bold</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.2dark_script</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>("Smith"|"Exit")</string>
			<key>name</key>
			<string>variable.parameter.2dark_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.2dark_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(Wait)\b</string>
			<key>name</key>
			<string>variable.parameter.2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>("[^"]*")</string>
			<key>name</key>
			<string>string.quoted.2dark_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.2dark_script</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted entity.name.function.2dark_script</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.2dark_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*(Event|Process)\s("[\w\_\-]+")\s*('.*)?$</string>
			<key>name</key>
			<string>2dark_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.2dark_script</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.2dark_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*(Variables)\s*('.*)?$</string>
			<key>name</key>
			<string>2dark_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.2dark_script</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.2dark_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*(Return)\s*('.*)?$</string>
			<key>name</key>
			<string>2dark_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.2dark_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*(Restart)\s*</string>
			<key>name</key>
			<string>2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^\s*\b(If|Else|EndIf|Switch|EndSwitch|Case|Default|Next|ListFor|For|While|Wend|Include|ClassScript)\b</string>
			<key>name</key>
			<string>keyword.control.2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(To|Step)\b</string>
			<key>name</key>
			<string>keyword.control.2dark_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.2dark_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*\b(Wait_)(Anim|Angle|Sound|SpatialSound|FadeIn|FadeOut|OnScreen|Goto|GotoPath|FollowEntity|FollowEntityPath|AngleObject)\b</string>
			<key>name</key>
			<string>entity.name.function.2dark_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.2dark_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(Stop_)(WaitSteering)\b</string>
			<key>name</key>
			<string>entity.name.function.2dark_script</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b((Substring|WaitStatus|Format|TargetAngle|Angle|Anim|Speed|GetPickupOwner|GetViewList|LifePoints|MaxSpeed|StringContains|ListContains|Attributes|ListIndex|ListCount|Rnd|isOnScreen|EventParameter|Distance|IsInventory|State|GetEtage|Room|IsAlive|#|Kind|RightHand|LeftHand|PickupCategory|Process|FollowDistance|GetEntityLightList|IsProcess)\b\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.2dark_script</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.2dark_script</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.2dark_script</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.2dark_script</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b((Substring|WaitStatus|Format|TargetAngle|Angle|Anim|Speed|GetPickupOwner|GetViewList|LifePoints|MaxSpeed|StringContains|ListContains|Attributes|ListIndex|ListCount|Rnd|isOnScreen|EventParameter|Distance|IsInventory|State|GetEtage|Room|IsAlive|#|Kind|RightHand|LeftHand|PickupCategory|Process|FollowDistance|GetEntityLightList|IsProcess)\b\s*[^\(])</string>
			<key>name</key>
			<string>invalid.deprecated.2dark_script</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.2dark_script</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.2dark_script</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*\b(SetEvent)(Enter|Exit|View|BlockedPath|ColPlayer|ColActor|Follow|Hit|Death|EnterRoom|HearSound|SeePlayer|SeeActor|SeeKid|Lit|UnLit|PlayerLit|Timer|Lost|EntityLight)\b</string>
			<key>name</key>
			<string>entity.name.function.2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^\s*\b(OpenProp|ScriptPlayerControl|SetCameraTarget|AmbientSoundStart|AmbientSoundVolume|AmbientSoundStop|EventOff|SetLifePoints|CallClassEvent|PortalTrigger|Immortal|UseRightHandPickup|SetHearAttributes|SetKind|CallEvent|SetAttributes|MusicVolume|ListReplace|ListRemove|CloseProp|RunProcess|Log|StoreItem|KillProcess|SetVariable|Message|DialogBox|TextBox|Bubble|Picture|SpatialSound|Sound|OpenDoor|CloseDoor|OpendDoor|LockPath|BlockedPath|SetPhysicMass|PickupItem|DropItem|SetEntityLightAttributes|TakeItem|RemoveItem|EquipRight|EquipLeft|SetState|Sleep|WakeUp|Teleport|Hit|SetAnim|SetAnimOnce|SetAnimStop|(?&lt;=Wait_)Anim|SetViewDistance|SetHearDistance|SetViewAperture|SetViewAttributes|SetFollowDistance|SetEventParameter|SetSpeed|SetAngle|SetAngleObject)\b</string>
			<key>name</key>
			<string>entity.name.function.2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(SourceName|SourceEntity|SourceParameter|SourceKind|TriggerName|TriggerEntity|TriggerParameter|TriggerKind|EventInfo)\b</string>
			<key>name</key>
			<string>variable.parameter.2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(int|string|entity|float|list)\b</string>
			<key>name</key>
			<string>storage.type.2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\+|\-|\*|/|\=|\&lt;\&gt;|\&lt;|\&gt;|\&gt;\=|\&lt;\=|~\=)</string>
			<key>name</key>
			<string>keyword.operator.2dark_script</string>
		</dict>
		<dict>
			<key>match</key>
			<string>('.*$)</string>
			<key>name</key>
			<string>comment.2dark_script</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.2dark_script</string>
	<key>uuid</key>
	<string>0da65be4-5aac-4b6f-8071-1aadb970b8d9</string>
</dict>
</plist>
